-- numbers 테이블 생성 스크립트 (대용량 더미 데이터용 카운터)
-- 목적: INSERT ... SELECT 시 반복 숫자 시퀀스를 제공하여 애플리케이션 루프 없이 대량 데이터 생성
-- 범위: 0 ~ 999,999 (총 100만 행), 03_posts_bulk_insert.sql 등에서 3회 UNION으로 300만 건 생성
-- 특징: DB 내부 연산만 사용, 테스트/성능 검증 전용 보조 테이블
-- 실행 후: SELECT COUNT(*) FROM numbers; 로 행 수 확인


USE weflow_local;

DROP TABLE IF EXISTS numbers;
CREATE TABLE numbers (n INT PRIMARY KEY) ENGINE=InnoDB;

INSERT INTO numbers (n)
SELECT a.N + b.N*10 + c.N*100 + d.N*1000 + e.N*10000 + f.N*100000
FROM (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
     (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
     (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
     (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d,
     (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e,
     (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) f
    LIMIT 3000000;

-- 실행 후
-- SELECT COUNT(*) FROM numbers;
